# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0ri3hm95cjqy54dg4161jf9icsybq01w5cpv4cvd148msyk2ym6s";
    aarch64-linux = "0cgbcmxk4fvvba98khras3cczwncb1xz9v2yhxj5yd1g67ybna51";
    x86_64-darwin = "098wmcfqmm7as6h3w4ramchbs9digdbgbp4bf5pdcnxaja6cpk9z";
    aarch64-darwin = "1559pnhsq956ghklgl7v55zv983apkjfid0pp6pkqc0mal2dvg3b";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.6/dir2mcp_0.9.6_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.6/dir2mcp_0.9.6_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.6/dir2mcp_0.9.6_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.6/dir2mcp_0.9.6_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dir2mcp";
  version = "0.9.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dir2mcp $out/bin/dir2mcp
  '';

  meta = {
    description = "Deploy any local directory as an MCP knowledge server with indexing, retrieval, and citations (lean binary).";
    homepage = "https://github.com/dirstral/dir2mcp";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
