# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "12bn92yg92xrhjwb2gc0s20babgkflarf0fwz22zvx4ispd3mnnm";
    aarch64-linux = "1j5jcngbxppfml7mchnci2afvh69nlsqbmdwb1chw2ig80isw5md";
    x86_64-darwin = "09kfmla3lm9pnfxlnrl06h5xzgvpdyxpbqqsnydssk39671wbjj1";
    aarch64-darwin = "01k91lh78njgbrk7ygsrpkw7kncc5rkfiz3s3naq9nsll7nny9i2";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.9/dir2mcp_0.9.9_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.9/dir2mcp_0.9.9_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.9/dir2mcp_0.9.9_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/dirstral/dir2mcp/releases/download/v0.9.9/dir2mcp_0.9.9_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dir2mcp";
  version = "0.9.9";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dir2mcp $out/bin/dir2mcp
  '';

  meta = {
    description = "Deploy any local directory as an MCP knowledge server with indexing, retrieval, and citations (lean binary).";
    homepage = "https://github.com/dirstral/dir2mcp";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
