# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1lr3kr2rv8ysqjrgg3cydzzacr3291whbggajjmg4a32xpl1xh62";
    aarch64-linux = "1w1pcc2yc6grcl54c9p382qd97rmadsbnb1aq3kw8z9fa1pv54hn";
    x86_64-darwin = "15imb44haadbbar9lcp7pkn11gq98ml15rh3w2d8x1zwin2jg4l5";
    aarch64-darwin = "1cnw0p17wycjablcmhz11wx71s7kphjymr2xlicgsxq487xwl004";
  };

  urlMap = {
    x86_64-linux = "https://github.com/dirstral/dir2mcp/releases/download/v0.11.3/dir2mcp_0.11.3_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/dirstral/dir2mcp/releases/download/v0.11.3/dir2mcp_0.11.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/dirstral/dir2mcp/releases/download/v0.11.3/dir2mcp_0.11.3_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/dirstral/dir2mcp/releases/download/v0.11.3/dir2mcp_0.11.3_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dir2mcp";
  version = "0.11.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./dir2mcp $out/bin/dir2mcp
    runHook postInstall
  '';

  meta = {
    description = "Deploy any local directory as an MCP knowledge server with indexing, retrieval, and citations (lean binary).";
    homepage = "https://github.com/dirstral/dir2mcp";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
